### ISSUE TITLE
Dragged method to new category, got error, method disappears

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#113] opened 2018-04-26 06:52 UTC
I was browsing RowanSample1, class RowanSample1XXX, and I dragged the method #'xxx' and dropped into the method protocol *rowansample1-extensions.

I got a walkback, 
a LookupError occurred (error 2021), reason:rtErrKeyNotFound, A reference using the non-existent key #'*rowansample1-extensions' was made into the dictionary aGsMethodDictionary

Now the method #'xxx' appears to be invisible, although I can still execute it.  

If I try Methods > Browse implmentors of... on xxx, I get another walkback, a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'do:'
which is apparently a consequence of whatever happened. 

----  following issue is slightly related... case-sensitivity of package names during load differing from behavior during development? ----

Thinking that the protocol name was an error I could fix, I managed with some difficulty to create a properly capitalized protocol name, and get the method #'xxxtension' into that protocol, and I can freely drag #'xxx' in and out.  

However, the package RowanSample1-Extensions show the method xxxtension removed and the package RowanSample1-XXX shows the method xxxtension added.  Counterintuitively.

**Comment by dalehenrich** [comment] 2018-04-26 07:07
a full stack would really help understand this ...

**Comment by dalehenrich** [comment] 2018-04-26 09:11
This looks to be similar to #111, but you are getting a wb and @ericwinger is not getting an error, but then he isn't seeing the changes either ...

I see from the stack that we are not calling the Rowan API for moving a method into a different --- because there isn't one at the moment:)

I will need to add an api for changing method protocol first

**Comment by ericwinger** [comment] 2018-04-26 18:05
From a clean load of Rowan and RowanSample1, I see the same behavior Lisa reported.

**Comment by dalehenrich** [comment] 2018-05-04 03:36
Isn't this actually issue #116 ... moveMethod:toCategory: now has a Rowan API (Behavior>>rwMoveMethod:toCategory:) ... so it is now in @ericwinger court

**Comment by LisaAlmarode** [comment] 2018-05-08 00:11
Still happening in latest ! 
Assign to Dale since Eric does appear to be calling Behavior>>rwMoveMethod:toCategory: as instructed.  

--------------------------
a LookupError occurred (error 2015), reason:objErrNotInColl, The object #'anotherMethodOne' was not found in the collection aSymbolSet( ).

LookupError (AbstractException) >> _signalWith: @5 line 25
LookupError (AbstractException) >> signal @2 line 47
SymbolSet (Object) >> _error:args: @15 line 11
SymbolSet (Collection) >> _errorNotFound: @2 line 5
SymbolSet (IdentityBag) >> remove: @2 line 8
RwGsSymbolDictionaryRegistry >> moveCompiledMethod:toProtocol: @21 line 25
RwGsMethodPropertiesSymDictPatch >> installPropertiesPatchNewClasses:andExistingClasses: @17 line 20
[] in  ExecBlock1 (RwGsPatchSetBasic) >> updateMethodProperties @2 line 4
[] in  ExecBlock1 (Set) >> do: @2 line 11
[] in  ExecBlock2 (KeyValueDictionary) >> keysDo: @2 line 7
KeyValueDictionary >> keysAndValuesDo: @23 line 20
KeyValueDictionary >> keysDo: @2 line 6
Set >> do: @3 line 11
RwGsPatchSetBasic >> updateMethodProperties @2 line 4
RwGsPatchSetBasic >> apply @20 line 26
RwGsImage class >> applyModification:instanceMigrator: @11 line 10
RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @13 line 13
RwPrjLoadTool >> loadProjectSetDefinition: @4 line 4
RwPrjBrowserTool >> moveMethod:forClassNamed:isMeta:toProtocol: @79 line 80
LisaClassA class (Behavior) >> rwMoveMethod:toCategory: @8 line 4
[] in  ExecBlock1 (JadeServer) >> sbMethodCategory: @3 line 5
OrderedCollection (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> sbMethodCategory: @6 line 5
JadeServer64bit32 (JadeServer) >> systemBrowserCommand @125 line 41
[] in  ExecBlock0 (JadeServer) >> systemBrowserA: @14 line 10
Time class >> secondsElapsedTime: @5 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit32 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit32 (JadeServer) >> systemBrowserA: @2 line 4
JadeServer64bit32 (JadeServer) >> systemBrowser: @3 line 2
[] in  ExecBlock0 (JadeServer64bit) >> systemBrowser: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit) >> systemBrowser: @2 line 5
GsNMethod class >> _gsReturnToC @1 line 1

---- latest reproduction details ----

In packages tab, select RowanSample1-Core.
Create a class LisaClassA  and subclass of this, LisaClass B (subclass may not be relevant)
add an inst var to LisaClassA, aaa, this versions the class. (may or may not be relevant)
add method categories *RowanSample1-Core and accessing
add method aaa ^aaa to *RowanSample1-Core and aaa: val val := aaa to accessing.
create two more methods in accessing category, anotherMethodOne ^1 and anotherMethodTwo ^2.
drag anotherMethodOne to *RowanSample1-Core and get walkback:

**Comment by dalehenrich** [comment] 2018-05-10 16:36
The original bug did not require a new class version to reproduce ... if you create new class versions using session methods you will hit #125. [This is the current status](https://github.com/dalehenrich/Rowan/issues/125#issuecomment-386485365) --- I have prioritized loading Rowan with Rowan above fixing session method related bugs in Rowan ... I've also changed the RowanSample1 project to not use session methods for extension methods --- the more common use case for most commercial customers.  RowanSample2 still uses session methods if you want to exercise the session method code ... 

Here's the stack from one of two currently failing tests for session methods:
```
LookupError (AbstractException) >> _signalWith: @5 line 25
LookupError (AbstractException) >> signal @2 line 47
GsMethodDictionary (Object) >> _error:args: @15 line 11
GsMethodDictionary (AbstractDictionary) >> _errorKeyNotFound: @2 line 5
GsMethodDictionary (AbstractDictionary) >> at: @7 line 9
RwGsSymbolDictionaryRegistry >> moveCompiledMethod:toProtocol: @20 line 25
RwGsMethodPropertiesSymDictPatch >> installPropertiesPatchNewClasses:andExistingClasses: @17 line 20
[] in  ExecBlock1 (RwGsPatchSetBasic) >> updateMethodProperties @2 line 4
[] in  ExecBlock1 (Set) >> do: @2 line 11
[] in  ExecBlock2 (KeyValueDictionary) >> keysDo: @2 line 7
KeyValueDictionary >> keysAndValuesDo: @23 line 20
KeyValueDictionary >> keysDo: @2 line 6
Set >> do: @3 line 11
RwGsPatchSetBasic >> updateMethodProperties @2 line 4
RwGsPatchSetBasic >> apply @20 line 26
RwGsTestImage class (RwGsImage class) >> applyModification:instanceMigrator: @11 line 10
RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @13 line 13
RwPrjLoadTool >> loadProjectSetDefinition: @4 line 4
RwPrjBrowserTool >> moveMethod:forClassNamed:isMeta:toProtocol: @79 line 80
RwHybridBrowserToolTest >> testHybridMoveMethodFromSessionMethodsIntoSessionMethods @38 line 44
RwHybridBrowserToolTest (TestCase) >> performTest @3 line 2
[] in  ExecBlock0 (TestCase) >> runCase @3 line 5
ExecBlock0 (ExecBlock) >> ensure: @2 line 12
RwHybridBrowserToolTest (TestCase) >> runCase @4 line 6
[] in  ExecBlock0 (TestCase) >> debug @4 line 2
ExecBlock0 (ExecBlock) >> ensure: @2 line 12
RwHybridBrowserToolTest (TestCase) >> debug @2 line 3
RwHybridBrowserToolTest class (TestCase class) >> debug: @3 line 3
JadeServer64bit32 (JadeServer) >> debugTestNamed:of: @4 line 4
GsNMethod class >> _gsReturnToC @1 line 1
```
and while your failure and the test failure are both occurring on line 25, you are getting an error on the #remove: and the tests fail on the #at: ... I will record your stack and steps to reproduce in issue #125 and when if your scenario is still failing when I've fixed the underlying session method-related problems, then I will create another test case to reproduce your problem .

Closing in favor of #125

**Closed by dalehenrich** 2018-05-10 16:36 UTC
Labels: Alpha 1.1
