### ISSUE TITLE
Error on rowan-updating-rowan

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#216] opened 2018-06-11 20:48 UTC
1.  Setup a new stone (extents without rowan loaded).

   rowan git is on branch issue_208 and sha facfo7b.
   do normal rowan install, input ... install.tpz.

2.  login as system user from jadeite, do "pull from git".  

Verify git is on correct-ish sha; git log -1 sez:
```
commit 4273fcbf7cd6563f6f1092b8035ffefea0a93d4a
Author: Dale Henrichs <dale.henrichs@gemtalksystems.com>
Date:   Sun Jun 10 16:03:31 2018 -0700
    Issue #212: the tools classes are now in the RowanTools symbol dictionary
```
3.  In jadite, do git load. Get walkback.
```
UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsSymbolDictionaryRegistry (Object) >> error: @6 line 7
[] in  ExecBlock0 (RwGsSymbolDictionaryRegistry_Implementation class) >> _doDeleteCompiledMethodFromLoadedThings:for:instance: @2 line 10
IdentityKeyValueDictionary >> at:ifAbsent: @25 line 19
RwGsSymbolDictionaryRegistry_Implementation class >> _doDeleteCompiledMethodFromLoadedThings:for:instance: @3 line 7
RwGsSymbolDictionaryRegistry_Implementation class >> deleteMovedLoadedMethod:for:instance: @4 line 6
RwGsSymbolDictionaryRegistry >> deleteMovedLoadedMethod:for:implementationClass: @2 line 5
RwGsMethodDeletionExtensionSymbolDictPatch (RwGsMethodDeletionSymbolDictPatch) >> deleteMovedLoadedMethodNewClasses:andExistingClasses: @7 line 10
[] in  ExecBlock1 (RwGsPatchSet) >> deleteMovedLoadedExtensionMethods @2 line 4
[] in  ExecBlock1 (Set) >> do: @2 line 11
[] in  ExecBlock2 (KeyValueDictionary) >> keysDo: @2 line 7
KeyValueDictionary >> keysAndValuesDo: @18 line 15
KeyValueDictionary >> keysDo: @2 line 6
Set >> do: @3 line 11
RwGsPatchSet >> deleteMovedLoadedExtensionMethods @2 line 4
RwGsPatchSet >> apply @21 line 25
RwGsImage class >> applyModification:visitorClass:instanceMigrator: @11 line 10
RwGsImage class >> applyModification:instanceMigrator: @7 line 8
RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @17 line 28
[] in  ExecBlock0 (RwPrjLoadTool) >> loadProjectNamed:instanceMigrator: @2 line 9
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RwPrjLoadTool >> loadProjectNamed:instanceMigrator: @6 line 11
RwPrjLoadTool >> loadProjectNamed: @4 line 5
[] in  ExecBlock0 (RowanProjectService) >> loadProjectNamed: @4 line 3
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RowanProjectService >> loadProjectNamed: @3 line 4
GsNMethod class >> _gsReturnToC @1 line 1
```

**Comment by dalehenrich** [comment] 2018-06-11 21:29
This looks like a duplicate of Issue #215 ... and I am just about ready to commit my fix and update branch issue_208 and attempting to update Rowan across commit 249445e will result in this error ...

You'll need to start with commit 4273fcb and build from scratch .... I found this after doing basically the same thing you did (I frequently test Rowan updating Rowan and discovered the bug yesterday and started work on fixing it today ... sorry for not giving you a heads up)

**Comment by dalehenrich** [comment] 2018-06-11 21:42
If you want. I've just tagged `v0.2.5-alpha` which is now the latest version that can be used to update Rowan with Rowan ... you can start at this commit and the update to the latest issue_215 branch --- I've just fixed the bug and will be merging it into issue_208 branch in a minute or two

**Comment by dalehenrich** [comment] 2018-06-11 21:45
I have now updated issue_208 and deleted branch issue_215

**Closed** 2018-06-11 21:46 UTC
Labels: duplicate
