### ISSUE TITLE
Add-subclass template has empty category, package name set

### ISSUE THREAD

**Issue by LisaAlmarode** [dalehenrich/Rowan#138] opened 2018-05-01 03:05 UTC
It was quite confusing since I clicked elsewhere, came back, and my class categories pane did not show my new class at all.  

RowanSample1 rwSubclass: 'NameOfSubclass'
	instVarNames: #()
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: ''
	packageName: 'RowanSample1-Core'
	options: #()

**Comment by dalehenrich** [comment] 2018-05-01 04:36
Which view `packages` or `dictionaries` were you using?

**Comment by LisaAlmarode** [comment] 2018-05-01 06:14
Both

**Comment by ericwinger** [comment] 2018-05-02 00:43
Ok, I see the bug.  The new subclass was added and can be seen by selecting All Categories in the Class Categories pane. However selecting the class category RowanSample1 or it's subcategory Core will not show the new class. 

Workaround - Select All Categories to see the newly created class.

**Comment by ericwinger** [comment] 2018-05-02 00:44
Interesting, the Show Changes browser shows this modification which is wrong: 
```
RowanSample1 rwSubclass: '''NameOfSubclass'''
	instVarNames: #()
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: '''nil'''
	options: #()
```

**Comment by ericwinger** [comment] 2018-05-02 16:28
I think the problem is in this variant of the rwSubclass methods: 
```
Object rwSubclass: 'FooSub2'
	instVarNames: #()
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: ''
	packageName: 'NewPackage'
	options: #()
```
When I execute this in a workspace I see the problems described above. But when I execute this rwSubclass variant, both the Show Changes & missing category problem go away. 
```
Object rwSubclass: 'NameOfSubclass'
	instVarNames: #()
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'NewPackage'
	options: #()
```
Reassigning to Dale.

**Comment by ericwinger** [comment] 2018-05-02 16:38
Reassigning back to me. Should only use this variant in alpha: 
```
 Object rwSubclass: 'NameOfSubclass'
	instVarNames: #()
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'NewPackage'
	options: #()
```

**Closed** 2018-05-02 23:27 UTC
Labels: Alpha 1.1
