### ISSUE TITLE
RwResolvedProjectV2>>printOn: doesn't handle nil projectName

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#911] opened 2024-01-12 22:58 UTC
```
RwResolvedProjectV2>>printOn: 
printOn: aStream
	super printOn: aStream.
	projectDefinition
		ifNotNil: [ 
			aStream
				nextPutAll: ' for ';
				nextPutAll: self _projectDefinition projectName ]
```
If the projectName is nil, a MNU occurs. Stack attached. I don't know how the definition's projectName became nil. I was inspecting what I thought was a well-formed RwGsLoadedSymbolDictResolvedProjectV2. 

![image](https://github.com/GemTalk/Rowan/assets/36212516/37b197e8-ece0-46de-bbe6-b44b3ef6123e)

[2024-01-12_12838115_rowanServerStackDump.txt](https://github.com/GemTalk/Rowan/files/13924820/2024-01-12_12838115_rowanServerStackDump.txt)

**Comment by ericwinger** [comment] 2024-01-12 23:00
It looks like clicking on the `handle` inst var reproduces the walkback. The project was retrieved from Rowan using `Rowan image loadedProjects`

**Comment by dalehenrich** [comment] 2024-01-12 23:04
duplicate of issue #775

**Closed as completed by dalehenrich** 2024-01-12 23:04 UTC
Labels: duplicate

**Comment by dalehenrich** [comment] 2024-01-12 23:06
add `next up` tag to #775 ... two reports for same bug, merits a bump in priority ...
